name: MituvaMenu
version: BETA_0.1
main: org.mituba01.mituvamenu._01
api-version: '1.20'
commands:
  menu:
    description: Opens the Mituva menu
    usage: /<command>
  menureload:
    description: Reloads the Mituva menu configuration
    usage: /<command>
    permission: mituvamenu.reload